### ISSUE TITLE
OAuth Connection issue

### ISSUE THREAD

**Issue by khaledbk** [CartoDB/carto-react#296] opened 2022-01-23 01:59 UTC
Hi, 
I was trying to run this container in a separate server, and finally everything works great! 
After while i was trying to create an Application under `/oauth_apps` and i got my `clientId` to use with my carto react app, unfortunately, i had this problem : 
![Screenshot from 2022-01-23 02-51-27](https://user-images.githubusercontent.com/17870364/150661488-1e337505-8f02-4a25-9f33-652e31747c29.png)
 
I wsa trying to connect to my self hosted container for this purpose, but while using the official cartodb server, i do not have the same error, and i was able to connect successfully to my react app.
I had to change the `credentials.apiBaseUrl` `oauth.domain` `oauth.audience` `oauth.authorizeEndPoint` ... 

`"@auth0/auth0-react": "^1.8.0",`
`"@carto/react-api": "^1.1.0",`
`"react": "^17.0.2",`

Thank You !

**Comment by borja-munoz** [comment] 2022-01-24 08:45
Hi Khaled,

Glad to hear you could connect.

Closing this issue.

Thanks!

**Comment by khaledbk** [comment] 2022-01-24 08:49
> Hi Khaled,
> 
> Glad to hear you could connect.
> 
> Closing this issue.
> 
> Thanks!

I'm still trying ...

**Comment by borja-munoz** [comment] 2022-01-24 09:23
I'm sorry, I thought you had been able to connect.

Could you please share some information about your environment? (i.e. which CARTO platform version you are using, 2 or 3?, which CARTO for React template?)

Thanks

**Comment by khaledbk** [comment] 2022-01-24 16:19
@borja-munoz , i'm currently using CARTO version 3 , i created my app using `npx create-react-app my-app --template @carto/base-3` 

This is a list of my `dependencies` , 
`"dependencies": {
    "@auth0/auth0-react": "^1.8.0",
    "@carto/react-api": "^1.1.0",
    "@carto/react-basemaps": "^1.1.0",
    "@carto/react-core": "^1.1.0",
    "@carto/react-redux": "^1.1.0",
    "@carto/react-ui": "^1.1.0",
    "@carto/react-widgets": "^1.1.0",
    "@carto/react-workers": "^1.1.0",
    "@deck.gl/carto": "^8.6.5",
    "@emotion/react": "^11.7.1",
    "@emotion/styled": "^11.6.0",
    "@formatjs/intl-getcanonicallocales": "^1.8.0",
    "@formatjs/intl-locale": "^2.4.42",
    "@formatjs/intl-numberformat": "^7.3.1",
    "@formatjs/intl-pluralrules": "^4.2.1",
    "@material-ui/core": "^4.12.3",
    "@material-ui/icons": "^4.11.2",
    "@material-ui/lab": "^4.0.0-alpha.60",
    "@mui/icons-material": "^5.2.5",
    "@mui/material": "^5.2.7",
    "@mui/x-data-grid": "^5.2.2",
    "@reduxjs/toolkit": "^1.7.1",
    "@testing-library/jest-dom": "^5.16.1",
    "@testing-library/react": "^12.1.2",
    "@testing-library/user-event": "^13.5.0",
    "@turf/bbox-polygon": "^6.5.0",
    "@turf/boolean-intersects": "^6.5.0",
    "apexcharts": "^3.32.1",
    "deck.gl": "^8.6.5",
    "deepmerge": "^4.2.2",
    "distinct-colors": "^3.0.0",
    "echarts": "^5.2.2",
    "echarts-for-react": "^3.0.2",
    "eslint-config-prettier": "^8.3.0",
    "eslint-plugin-prettier": "^3.4.1",
    "history": "^5.2.0",
    "husky": "^7.0.4",
    "hygen": "^6.1.0",
    "lint-staged": "^11.2.6",
    "lodash": "^4.17.21",
    "prettier": "^2.5.1",
    "react": "^17.0.2",
    "react-apexcharts": "^1.3.9",
    "react-app-polyfill": "^2.0.0",
    "react-app-rewired": "^2.1.11",
    "react-dom": "^17.0.2",
    "react-is": "^17.0.2",
    "react-map-gl": "^5.3.18",
    "react-redux": "^7.2.6",
    "react-router-dom": "^6.2.1",
    "react-scripts": "^4.0.3"
  },`

Thank you

**Comment by khaledbk** [comment] 2022-01-24 17:08
currently i'm using this image `https://hub.docker.com/r/sverhoeven/cartodb/` , witch use the latest `cartodb` version

**Comment by borja-munoz** [comment] 2022-01-24 17:24
This image is using version 2 of the CARTO platform. You cannot use the base-3 template because it is designed to work with CARTO 3. You could try to use one of the templates for CARTO 2 but we cannot guarantee it is going to work because we have not tested them against this particular image.

**Comment by khaledbk** [comment] 2022-01-24 17:33
thank you for your response i will try it now

**Comment by alasarr** [comment] 2022-10-22 09:19
Closing this. Feel free to reopen @khaledbk if the issue is still there

**Closed by alasarr** 2022-10-22 09:19 UTC
